name: CI TP

on:
  push:
    branches:
      - develop

jobs:
  test-memory:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find JPEG files
        id: find-jpgs
        run: |
          jpg_files=$(find /home/kento/tpDevops/memory/html/data -type f -iname "*.jpg")
          for file in $jpg_files; do
            echo "jpg_files=${file}" >> $GITHUB_ENV
          done

      - name: Check JPEG files
        run: |
          set -e  # Arrête le script à la première erreur
          for file in ${{ env.jpg_files }}; do
            echo "Vérification de $file..."
            if ! file "$file" | grep -q "JPEG image data"; then
              echo "JPEG corrompu: $file"
              cp /home/kento/images/image0.jpg "$file"
              echo "Remplacement de $file par image0.jpg"
            else
              echo "$file OK."
            fi
          done

  build-memory:
    runs-on: self-hosted
    needs: test-memory

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/memory .


  push-memory:
    runs-on: self-hosted
    needs: build-memory

    steps:
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/memory

  deploy-memory:
    runs-on: self-hosted
    needs: push-memory

    steps:
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 kento@localhost "
            cd /home/kento/tpDevops/memory &&
            docker-compose pull &&
            docker-compose up -d
          "





