name: CI TP

on:
  push:
    branches:
      - develop

jobs:
  test-memory:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find JPEG files
        id: find-jpgs
        run: |
          jpg_files=$(find . -type f -iname "*.jpg")
          echo "jpg_files=${jpg_files}" >> $GITHUB_ENV

      - name: Check JPEG files
        run: |
          for file in $jpg_files; do
            if ! file "$file" | grep -q "JPEG image data"; then
              echo "JPEG corrompu: $file"
              cp /home/kento/images/image0.jpg "$file"
              echo "Remplacement de $file"
            else
              echo "$file OK."
            fi
          done
